version = 0.1
[default.deploy.parameters]
stack_name = "noti-responsabilidades"
resolve_s3 = true
s3_prefix = "noti-responsabilidades"
region = "us-east-1"
profile = "pdesarrollo"
capabilities = "CAPABILITY_IAM"
image_repositories = []
